function myBirthYearFunc(){
        console.log("Nací en " + 1980);
    }
    //el console.log imprime "naci en 1980"


function myBirthYearFunc(EntradaAñoNacimiento){
        console.log("Nací en " + EntradaAñoNacimiento);
    }
//el console.log imprime "Nací en 2005 (EntradaAñoNacimiento)"


function add(num1, num2){
        console.log("¡Sumando números!");
        console.log("num1 is: " + num1);
        console.log("num2 is: " + num2);
        var sum = num1 + num2;
        console.log(sum);
    }
    

 //el console.log Imprime el resultado de la suma
 